### ISSUE TITLE
 Error: 'ct_read_trial_csv' is not an exported object from 'namespace:clinicaltrialr' 

### ISSUE THREAD

**Issue by OleksiyAnokhin** [serghiou/clinicaltrialr#1]
Hi. I am going through your sample code and receive this error. How to resolve it? 

    library(pbapply)

    trials_list <- pbapply::pblapply(results$`NCT Number`, read_trials, cl = 7)
    trials <- dplyr::bind_rows(trials_list)

     Error: 'ct_read_trial_csv' is not an exported object from 'namespace:clinicaltrialr'

**Comment by serghiou** [comment]
Hi! Thanks for issuing a bug. The example was using a previous version of the package. This has now been resolved.

**Comment by OleksiyAnokhin** [comment]
Thanks!

**Comment by serghiou** [comment]
You should be able to use the updated example at README.md
<https://github.com/serghiou/clinicaltrialr#readme>
